### ISSUE TITLE
Qt5 port

### ISSUE THREAD

**Issue by sl1pkn07** [amichaeltm/BDSup2SubPlusPlus#15]
Hi

Qt4 is deprecated/EOL sice years

any plan to port to Qt5?

greetings

**Comment by Selur** [comment]
compiles fine using Qt Creator and MSVC on Windows when replacing
` QMAKE_CXXFLAGS` += -std=c++14
with 
```
win32-msvc* {
  QMAKE_CXXFLAGS += /std:c++14
} else {
  QMAKE_CXXFLAGS += -std=c++14
}
```
in the .pro file.
iirc '-std=c++14' should work fine with mingw and clang as compiler.

**Comment by sl1pkn07** [comment]
oh, then NVM

builds perfect in my linux without touch anything

closing
