### ISSUE TITLE
global offsets > 0 in IDX lead to wrong image size

### ISSUE THREAD

**Issue by pprkut** [amichaeltm/BDSup2SubPlusPlus#22]
I'm trying to load vobsub subtitles into BDSup2Sub++, but I'm running into an issue where the image size is calculated wrongly for all subtitles except the first one. See screenshot for example:

![screenshot](https://user-images.githubusercontent.com/56635/110207057-9e7ff900-7e81-11eb-95a2-291141295d34.png)

I found a changelog entry in BDSup2Sub (3.7.1 -> 3.8.0) that looks exactly like the issue I'm having:
```
Fixed: VobSub: global offsets > 0 in IDX led to wrong image size (and wrong RLE decoding in some cases).
```

**Comment by captainayy** [comment]
It was not related to that. I have a fix for this issue that I'll send a pull request for.

**Comment by captainayy** [comment]
This is now fixed with the pull request.
