### ISSUE TITLE
Save new forced captions directly

### ISSUE THREAD

**Issue by hubblec4** [amichaeltm/BDSup2SubPlusPlus#7]
For now you have to set the new forced sups, then save the entire sup with the new forced sups.
Then load the new sup file and then save forced sups.

It would be great to save the new forced sups directly.

**Comment by amichaeltm** [comment]
Can you explain this more? I'm not understanding what you are saying. What do you mean by "save the new forced sups directly"?

**Comment by hubblec4** [comment]
Sometimes is on Blur-ray a sup stream without forced captions(but some captions should be) and no extra forced sup file.
I load this sup file and set some captions as forced. Now I click on save, the save dialog opens but the checkbox "Export only forced" is disabled(gray). I must save the entire new sup with forced captions, then I have to load the new sup file and can save the "only forced" captions to new forced_only_sup file.

What I want is that I can save the forced captions to a new forced_only_sup file directly after I set the new forced captions.

**Comment by amichaeltm** [comment]
Ok. Thanks. That helps.

**Comment by hubblec4** [comment]
OK, I understand and hope you can change this behavior.

**Comment by amichaeltm** [comment]
I will definitely change it. Just requires a bit of refactoring work.

**Comment by hubblec4** [comment]
Splendid, and many thanks.

**Comment by amichaeltm** [comment]
Fixed with 0b243caccdcab1fc68b29b4b45b6b29ff2ef1b65

**Comment by hubblec4** [comment]
Many Thanks.
